"""create_engineering_knowledge_tables

Revision ID: cd0314481fc2
Revises: a4b9d1a681ab
Create Date: 2026-10-02 12:46:43.523204

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0314481fc2'
down_revision: Union[str, None] = 'a4b9d1a681ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_knowledge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='knowledgestatus'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engineering_knowledge_created_at', 'engineering_knowledge', ['created_at'], unique=False)
    op.create_index(op.f('ix_engineering_knowledge_name'), 'engineering_knowledge', ['name'], unique=True)
    op.create_index('ix_engineering_knowledge_status', 'engineering_knowledge', ['status'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='knowledgestatus'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['engineering_knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_id', 'filename', name='uq_knowledge_documents_knowledge_id_filename')
    )
    op.create_index(op.f('ix_knowledge_documents_knowledge_id'), 'knowledge_documents', ['knowledge_id'], unique=False)
    op.create_index('ix_knowledge_documents_knowledge_id_filename', 'knowledge_documents', ['knowledge_id', 'filename'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['engineering_knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunks_document_id_chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_document_id_chunk_index', 'knowledge_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_id'), 'knowledge_chunks', ['knowledge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_document_id_chunk_index', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_documents_knowledge_id_filename', table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_engineering_knowledge_status', table_name='engineering_knowledge')
    op.drop_index(op.f('ix_engineering_knowledge_name'), table_name='engineering_knowledge')
    op.drop_index('ix_engineering_knowledge_created_at', table_name='engineering_knowledge')
    op.drop_table('engineering_knowledge')
    # ### end Alembic commands ###
